'use client'
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import api from '@/lib/axios'
import type { Document as IBFSDocument } from '@/models/document'
import { fmtAmount, fmtDate } from '@/lib/utils'
import { Button } from '@/components/ui/button'
type SavedSnapshot = IBFSDocument & { contact_id: number | null; reference_id: number | null; consignee_id: number | null }
interface Revision { id: number; recorded_at: string; event: string; changed_fields: string[]; doc_id: string; date: string; total_amount: string | null }
const fieldNames: Record<string, string> = { doc_id: 'document number', contact_id: 'contact', consignee_id: 'consignee', reference_id: 'reference', line_items: 'items', total_amount: 'total', charges: 'charges', taxes: 'taxes', tax_mode: 'tax rates', supply_category: 'classification', supplier_invoice_number: 'supplier invoice number', discount: 'discount', date: 'date', due_date: 'due date', payment_terms: 'terms', place_of_supply: 'place of supply', reverse_charge: 'reverse charge', attachment_urls: 'attachments', notes: 'notes', is_active: 'archive status', stock_mode: 'inventory control', is_paid: 'paid label' }

export function DocumentHistory({ id }: { id: number }) {
  const [open, setOpen] = useState(false)
  const [page, setPage] = useState(1)
  const [selected, setSelected] = useState<number | null>(null)
  const [itemPage, setItemPage] = useState(1)
  const query = useQuery({ queryKey: ['document-history', id, page], queryFn: () => api.get<{ count: number; results: Revision[] }>(`/documents/${id}/history/`, { params: { page, page_size: 10 } }).then(r => r.data), enabled: open })
  const version = useQuery({ queryKey: ['document-version', id, selected], queryFn: () => api.get<{ snapshot: SavedSnapshot }>(`/documents/${id}/history/`, { params: { revision: selected } }).then(r => r.data), enabled: open && selected !== null })
  const snapshot = version.data?.snapshot
  return <section className="px-4 py-5 border-t space-y-3"><Button variant="outline" size="sm" aria-expanded={open} onClick={() => setOpen(value => !value)}>Saved document versions</Button>{open && <><p className="text-xs text-muted-foreground">Versions are recorded from this release onward. A baseline preserves the known document before its first tracked edit. These are saved book versions; filing status is not inferred.</p>{query.isPending ? <p role="status">Loading versions…</p> : query.isError ? <p role="alert">Could not load versions. <Button variant="ghost" onClick={() => query.refetch()}>Retry</Button></p> : <>{!query.data?.count && <p className="text-sm text-muted-foreground">No tracked edits yet.</p>}{query.data?.results.map(row => <div className="rounded-lg border p-3 text-sm space-y-1" key={row.id}><div className="flex justify-between gap-3"><p className="font-semibold">{row.event === 'baseline' ? 'Known baseline' : row.event === 'archived' ? 'Archived' : row.event === 'created' ? 'Created' : 'Updated'} · {row.doc_id}</p><p>{row.total_amount === null ? '—' : fmtAmount(row.total_amount)}</p></div><p className="text-xs text-muted-foreground">Recorded {new Date(row.recorded_at).toLocaleString()} · Document date {fmtDate(row.date)}</p>{row.changed_fields.length > 0 && <p className="text-xs text-muted-foreground">Changed: {row.changed_fields.map(field => fieldNames[field] || field.replaceAll('_', ' ')).join(', ')}</p>}<Button variant="ghost" size="sm" onClick={() => { setSelected(row.id); setItemPage(1) }}>View saved version</Button></div>)}{(query.data?.count ?? 0) > 10 && <div className="flex justify-between"><Button size="sm" variant="outline" disabled={page === 1} onClick={() => setPage(value => value - 1)}>Previous versions</Button><Button size="sm" variant="outline" disabled={page * 10 >= query.data!.count} onClick={() => setPage(value => value + 1)}>Next versions</Button></div>}</>}
    {selected !== null && <div className="border rounded-xl p-4 space-y-3"><div className="flex justify-between"><h3 className="font-semibold text-sm">Saved version</h3><Button variant="ghost" size="sm" onClick={() => setSelected(null)}>Close version</Button></div>{version.isPending ? <p role="status">Loading saved values…</p> : version.isError ? <p role="alert">Could not load this version.</p> : snapshot && <><p className="text-sm">{snapshot.doc_id} · {fmtDate(snapshot.date)}{snapshot.total_amount !== null ? ` · ${fmtAmount(snapshot.total_amount)}` : ''}</p>{snapshot.contact_id && <a href={`/contacts/${snapshot.contact_id}`} className="text-primary text-xs">Contact #{snapshot.contact_id}</a>}{snapshot.reference_id && <a href={`/documents/${snapshot.reference_id}`} className="text-primary text-xs block">Reference document #{snapshot.reference_id}</a>}{snapshot.supply_category && <p className="text-xs">Supply: {snapshot.supply_category.replaceAll('_', ' ')}</p>}{snapshot.supplier_invoice_number && <p className="text-xs">Supplier invoice: {snapshot.supplier_invoice_number}</p>}{snapshot.notes && <p className="text-sm whitespace-pre-wrap break-words">{snapshot.notes}</p>}<div className="space-y-2">{(snapshot.line_items ?? []).slice((itemPage - 1) * 50, itemPage * 50).map((item, index) => <div key={index} className="text-sm border-t pt-2"><div className="flex justify-between gap-3"><p className="break-words">{item.name}</p><p className="shrink-0">{item.amount === undefined ? '—' : fmtAmount(item.amount)}</p></div>{item.hsn && <p className="text-xs text-muted-foreground">HSN/SAC {item.hsn}</p>}{item.quantity !== undefined && <p className="text-xs text-muted-foreground">Quantity {item.quantity}{item.unit ? ` ${item.unit}` : ''}{item.rate !== undefined ? ` · Rate ${fmtAmount(item.rate)}` : ''}</p>}{snapshot.tax_mode === 'item' && item.taxes?.map((tax, i) => <p className="text-xs text-muted-foreground" key={i}>{tax.name} {tax.percentage}%</p>)}</div>)}</div>{snapshot.line_items.length > 50 && <div className="flex justify-between"><Button size="sm" variant="outline" disabled={itemPage === 1} onClick={() => setItemPage(value => value - 1)}>Previous items</Button><Button size="sm" variant="outline" disabled={itemPage * 50 >= snapshot.line_items.length} onClick={() => setItemPage(value => value + 1)}>Next items</Button></div>}<div className="text-xs text-muted-foreground space-y-1">{snapshot.charges?.map((charge, i) => <p key={i}>{charge.name}: {fmtAmount(charge.amount)}</p>)}{snapshot.taxes?.map((tax, i) => <p key={i}>{tax.name}: {tax.percentage}%</p>)}{Number(snapshot.discount) > 0 && <p>Discount: {fmtAmount(snapshot.discount)}</p>}</div></> }</div>}
  </>}</section>
}
