const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { globSync } = require('./index.cjs')
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ibfs-root-glob-'))
try {
  fs.mkdirSync(path.join(root, 'apps', 'billing'), { recursive: true })
  fs.mkdirSync(path.join(root, 'apps', 'inventory'), { recursive: true })
  fs.writeFileSync(path.join(root, 'apps', 'notes.txt'), 'fixture')
  assert.deepEqual(globSync('apps/*', { cwd: root, onlyDirectories: true }).sort(), ['apps/billing', 'apps/inventory'])
  assert.deepEqual(globSync('apps/{billing,inventory}', { cwd: root, onlyDirectories: true }).sort(), ['apps/billing', 'apps/inventory'])
  assert.deepEqual(globSync('missing/*', { cwd: root, onlyDirectories: true }), [])
  assert.throws(() => globSync('*', { unknown: true }), /Unsupported/)
  const { createRequire } = require('node:module')
  const pluginRequire = createRequire(require.resolve('@next/eslint-plugin-next'))
  assert.equal(pluginRequire('fast-glob').globSync.toString(), globSync.toString())
  const { getRootDirs } = require('@next/eslint-plugin-next/dist/utils/get-root-dirs')
  const dirs = getRootDirs({ cwd: root, settings: { next: { rootDir: path.join(root, 'apps/*') } } })
  assert.equal(dirs.length, 2)
  assert.ok(dirs.every(dir => /billing|inventory/.test(dir)))
  console.log('Next root-directory glob and pinned plugin integration checks passed')
} finally { fs.rmSync(root, { recursive: true, force: true }) }
